version: '3.8'

services:
    frontend:
        container_name: secure_otp-frontend
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - TFA_BACKEND_URL=${BACKEND_URL}
            - TFA_OTP_WAIT_TIME=${OTP_WAIT_TIME}
            - TFA_REDIRECT_WAIT_TIME=${REDIRECT_WAIT_TIME}
        ports:
            - ${EXPOSE_PORT}:4200
