version: '3.8'

services:
    frontend:
        networks:
            - secure_otp-network
        build:
            target: development
        volumes:
            - ./:/usr/src/app
        environment:
            - NODE_ENV=development
        command: npm run start

networks:
    secure_otp-network:
        name: secure_otp-network
        driver: bridge
