services:
    frontend:
        extends:
            file: docker-compose.yml
            service: frontend
        volumes:
            - ./dist:/usr/src/app/dist
        networks:
            - secure_otp-network
        build:
            target: production
        environment:
            - NODE_ENV=production
