services:
    frontend:
        build:
            target: development
        volumes:
            - ./:/usr/src/app
        environment:
            - NODE_ENV=development
        command: npm run start
